watson-developer-cloud/doc-tutorial-downloads

speech-to-text/testSTTcustom.py

German, can you approve this one, too.  I know you hate the name; it's not mine.

STT: Update customization test script for December 2016 release.

---

README.md

Update link to conversation tutorial in README

---

speech-to-text/testSTTcustom.py
speech-to-text/testSTTcustom.sh

Kaylyn, can you please merge this PR that updates the STT customization scripts?  Thanks.

STT 1500: Add shell script and update Python script for customization.

---

README.md

- Update converted links
- Add WVA
- Fix capitalization

Update links after markdown conversion

---

personality-insights/profile.json
personality-insights/profile.txt

Current files are in WDC, so copying to this repo for use from bluemix

Add files to support docs in Bluemix

---

tradeoff-analytics/problem.json

Rick, hopefully you can approve a PR in this repo?

Tradeoff Analytics:  Move JSON file to downloads repo

---

tone-analyzer/tone-example1.json
tone-analyzer/tone-example2.json

I think I did this correctly, Rick.  It's a couple of updates for the Tone examples.  Let me know of any questions or problems.  -jeff

Tone Analyzer: Update example input files

---

dialog/Exercise_1_end.xml
dialog/Exercise_2_end.xml
dialog/Exercise_3_end.xml
dialog/Exercise_4_end.xml
dialog/Exercise_5_end.xml
dialog/Exercise_6_start.xml
dialog/Exercise_7_end.xml
dialog/Exercise_8_end.xml
dialog/WatsonDialogDocument_1.1.xsd
dialog/dnr_example.xml

Rick, the Dialog service downloads were never moved to this repo.  This PR moves all of them here as they exist with no other changes.  This is required for the conversion to Bluemix.

Move Dialog download files from old repo.

---

speech-to-text/testSTTcustom.py
speech-to-text/testSTTcustom.sh

`/common/` content is now in Bluemix.

Update links to docs

---

README.md
speech-to-text/testSTTcustom.py
speech-to-text/testSTTcustom.sh

- Update links that go to WDC to point to IBM Cloud
- Update references of Bluemix to IBM Cloud  (except for files for
deprecated services)
- Add Discovery to readme
- Remove deprecated services from readme

Update links and names

---

discovery/expansions.json

Discovery: Remove multi-word strings.

---

speech-to-text/grammars/confirm.abnf
speech-to-text/grammars/optional.abnf
speech-to-text/grammars/vins.abnf

Improve the formatting of a few of the ABNF grammars.

Clean up a few of the grammars.

---

speech-to-text/speech-override.yaml

I am copying Rick's idea for making the full Speech override file available to users to download.

8409: Copy Rick's notion of making full Speech override file available.

---

discovery-data/2.1.3/all-backup-restore.sh
discovery-data/2.1.3/elastic-backup-restore.sh
discovery-data/2.1.3/etcd-backup-restore.sh
discovery-data/2.1.3/hdp-backup-restore.sh
discovery-data/2.1.3/lib/function.bash
discovery-data/2.1.3/migrate-box-credential.sh
discovery-data/2.1.3/migrate-crawler-jar.sh
discovery-data/2.1.3/minio-backup-restore.sh
discovery-data/2.1.3/post-restore.sh
discovery-data/2.1.3/postgresql-backup-restore.sh
discovery-data/2.1.3/run-migrator.sh
discovery-data/2.1.3/run-postgres-config-job.sh
discovery-data/2.1.3/src/list_files_to_be_resourced.py
discovery-data/2.1.3/src/make_box_mapping.py
discovery-data/2.1.3/src/migrate_box_crawler.py
discovery-data/2.1.3/src/update_crawler_conf.py
discovery-data/2.1.3/src/update_jdbc_salesforce_conf.py
discovery-data/2.1.3/wddata-backup-restore.sh
discovery-data/2.1/all-backup-restore.sh
discovery-data/2.1/elastic-backup-restore.sh
discovery-data/2.1/etcd-backup-restore.sh
discovery-data/2.1/hdp-backup-restore.sh
discovery-data/2.1/lib/function.bash
discovery-data/2.1/post-restore.sh
discovery-data/2.1/postgresql-backup-restore.sh
discovery-data/2.1/run-postgres-config-job.sh
discovery-data/2.1/src/update_crawler_conf.py
discovery-data/2.1/wddata-backup-restore.sh

This PR will make the more rich logging on the backup or restore of Watson Discovery on ICP4D. It also add the scripts to migrating crawlers to Watson Discovery 2.1.3 from older version.

Logging and Crawler Migration for Backup Restore of Watson Discoevry on ICP4D

---

discovery-data/2.1.3/all-backup-restore.sh
discovery-data/2.1.3/lib/function.bash
discovery-data/2.1.3/lib/restore-updates.bash
discovery-data/2.1.3/post-restore.sh
discovery-data/2.1.3/run-postgres-config-job.sh
discovery-data/2.1.3/version.txt

Update the backup and restore scripts to support the Watson Discovery v2.1.4 on CP4D.

Update the backup/restore scripts for Watson Discovery v2.1.4 on CP4D

---

discovery-data/2.1.3/lib/function.bash
discovery-data/2.1.3/postgresql-backup-restore.sh
discovery-data/2.1.3/src/remove-etcd-keys.etcdupdate
discovery-data/2.1.3/version.txt
discovery-data/2.2.0/all-backup-restore.sh
discovery-data/2.2.0/elastic-backup-restore.sh
discovery-data/2.2.0/etcd-backup-restore.sh
discovery-data/2.2.0/lib/function.bash
discovery-data/2.2.0/lib/restore-updates.bash
discovery-data/2.2.0/minio-backup-restore.sh
discovery-data/2.2.0/post-restore.sh
discovery-data/2.2.0/postgresql-backup-restore.sh
discovery-data/2.2.0/run-migrator.sh
discovery-data/2.2.0/run-postgres-config-job.sh
discovery-data/2.2.0/src/clear_dfs.pgupdate
discovery-data/2.2.0/src/migrator-job-template.yml
discovery-data/2.2.0/src/minio_exclude_paths
discovery-data/2.2.0/src/postgres-config-job-template.yml
discovery-data/2.2.0/src/remove-etcd-keys.etcdupdate
discovery-data/2.2.0/src/update-content-type.pgupdate
discovery-data/2.2.0/src/update-ingestion-conf.sh
discovery-data/2.2.0/src/update-wire.pgupdate
discovery-data/2.2.0/version.txt
discovery-data/2.2.0/wddata-backup-restore.sh

Updates:
- Add scripts for Watson Discovery 2.2.0 on CP4D.
- Some fix for Watson Discovery 2.1.3 and 2.1.4.
- Retry on the network error.
- Modify pod selection for backup of postgresql.
- Reduce the disk usage on backup of postgresql.

Update the backup/restore scripts for Watson Discovery on CP4D.

---

natural-language-understanding/custom_categories_example.ipynb

- Add custom categories training recipe notebook

 Add custom categories training tutorial

---

discovery-data/2.1.3/lib/function.bash
discovery-data/2.1.3/run-postgres-config-job.sh
discovery-data/2.1.3/src/minio_exclude_paths
discovery-data/2.2.0/all-backup-restore.sh
discovery-data/2.2.0/elastic-backup-restore.sh
discovery-data/2.2.0/etcd-backup-restore.sh
discovery-data/2.2.0/lib/function.bash
discovery-data/2.2.0/lib/restore-updates.bash
discovery-data/2.2.0/minio-backup-restore.sh
discovery-data/2.2.0/post-restore.sh
discovery-data/2.2.0/postgresql-backup-restore.sh
discovery-data/2.2.0/src/elastic-backup-restore-in-pod.sh
discovery-data/2.2.0/src/migrator-job-template.yml
discovery-data/2.2.0/src/minio-backup-restore-in-pod.sh
discovery-data/2.2.0/src/minio-client-job-template.yml
discovery-data/2.2.0/src/minio_exclude_paths
discovery-data/2.2.0/version.txt
discovery-data/2.2.0/wddata-backup-restore.sh

This PR includes script updates for backup/restore of Watson Discovery 2.2.1 on CP4D.
This also includes small fix for Watson Discovery 2.1.3 and 2.1.4.

Update backup restore scripts for Watson Discovery on CP4D

---

discovery-data/2.2.0/all-backup-restore.sh
discovery-data/2.2.0/etcd-backup-restore.sh
discovery-data/2.2.0/lib/function.bash
discovery-data/2.2.0/minio-backup-restore.sh
discovery-data/2.2.0/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.0.5 on CP4D.
This also improve to check status of data store.

Scripts update for Watson Discovery 4.0.5 on CP4D

---

discovery-data/2.2.0/all-backup-restore.sh
discovery-data/2.2.0/lib/function.bash
discovery-data/2.2.0/src/minio-backup-restore-in-pod.sh
discovery-data/2.2.0/src/minio_exclude_paths

This PR includes some fix for next release of Watson Discovery on CP4D.

Script update for next WatsonDiscovery release

---

discovery-data/2.2.0/all-backup-restore.sh
discovery-data/2.2.0/elastic-backup-restore.sh
discovery-data/2.2.0/etcd-backup-restore.sh
discovery-data/2.2.0/lib/function.bash
discovery-data/2.2.0/minio-backup-restore.sh
discovery-data/2.2.0/post-restore.sh
discovery-data/2.2.0/postgresql-backup-restore.sh
discovery-data/2.2.0/run-postgres-config-job.sh
discovery-data/2.2.0/src/create_service_instance_template.json
discovery-data/2.2.0/src/elastic-mt-migration.sh
discovery-data/2.2.0/src/minio-mt-migration.sh
discovery-data/2.2.0/src/postgresql-backup-restore-in-pod.sh
discovery-data/2.2.0/src/tenant_index_template.json
discovery-data/2.2.0/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.0.6 on CP4D.

Script update for Watson Discovery 4.0.6 on CP4D

---

discovery-data/2.2.0/elastic-backup-restore.sh
discovery-data/2.2.0/lib/function.bash
discovery-data/2.2.0/lib/restore-updates.bash
discovery-data/2.2.0/minio-backup-restore.sh
discovery-data/2.2.0/mt-mt-migration.sh
discovery-data/2.2.0/post-restore.sh
discovery-data/2.2.0/postgresql-backup-restore.sh
discovery-data/2.2.0/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.5.0 on CP4D.
This also improve scripts stability.

Scripts update for Watson Discovery 4.5.0 on CP4D

---

discovery-data/2.2.0/all-backup-restore.sh
discovery-data/2.2.0/elastic-backup-restore.sh
discovery-data/2.2.0/lib/function.bash
discovery-data/2.2.0/lib/restore-updates.bash
discovery-data/2.2.0/minio-backup-restore.sh
discovery-data/2.2.0/mt-mt-migration.sh
discovery-data/2.2.0/postgresql-backup-restore.sh
discovery-data/2.2.0/src/elastic-backup-restore-in-pod.sh
discovery-data/2.2.0/src/postgres-config-job-template.yml
discovery-data/2.2.0/src/postgresql-backup-restore-in-pod.sh
discovery-data/2.2.0/src/reindex_archived_indices.sh
discovery-data/2.2.0/st-mt-migration.sh
discovery-data/2.2.0/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.5.1 on CP4D.
This also improve scripts stability.
Fix migration issue of ElasticSearch from 4.0.5 or prior releases.

Scripts update for Watson Discovery 4.5.1 on CP4D

---

discovery-data/latest/all-backup-restore.sh
discovery-data/latest/elastic-backup-restore.sh
discovery-data/latest/lib/function.bash
discovery-data/latest/minio-backup-restore.sh
discovery-data/latest/mt-mt-migration.sh
discovery-data/latest/post-restore.sh
discovery-data/latest/src/elastic-backup-restore-in-pod.sh
discovery-data/latest/src/minio-backup-restore-in-pod.sh
discovery-data/latest/src/minio_exclude_paths
discovery-data/latest/st-mt-migration.sh
discovery-data/latest/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.5.3 on CP4D.
This also improve scripts stability.

Update scripts for WatsonDiscovert 4.5.3 on CP4D

---

discovery-data/latest/lib/function.bash
discovery-data/latest/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.6.0 on CP4D.

Update scripts for WatsonDiscovery 4.6.0 on CP4D

---

discovery-data/latest/elastic-backup-restore.sh
discovery-data/latest/lib/function.bash
discovery-data/latest/src/elastic-backup-restore-in-pod.sh
discovery-data/latest/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.6.2 on CP4D.

Update scripts for WatsonDiscovert 4.6.2 on CP4D

---

discovery-data/latest/lib/function.bash
discovery-data/latest/src/elastic-backup-restore-in-pod.sh
discovery-data/latest/st-mt-migration.sh
discovery-data/latest/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.6.3 on CP4D.

Update scripts for WatsonDiscovert 4.6.3 on CP4D

---

discovery-data/latest/version.txt

This PR includes script updates for backup/restore of Watson Discovery 4.6.5 on CP4D.

Update script version for Watson Discovery 4.6.5 on CP4D

---

discovery-data/latest/all-backup-restore.sh
discovery-data/latest/elastic-backup-restore.sh
discovery-data/latest/etcd-backup-restore.sh
discovery-data/latest/lib/function.bash
discovery-data/latest/minio-backup-restore.sh
discovery-data/latest/mt-mt-migration.sh
discovery-data/latest/post-restore.sh
discovery-data/latest/postgresql-backup-restore.sh
discovery-data/latest/run-migrator.sh
discovery-data/latest/run-postgres-config-job.sh
discovery-data/latest/src/check_s3_status.sh
discovery-data/latest/src/elastic-backup-restore-in-pod.sh
discovery-data/latest/src/elastic-mt-migration.sh
discovery-data/latest/src/migrator-job-template.yml
discovery-data/latest/src/minio-backup-restore-in-pod.sh
discovery-data/latest/src/minio-mt-migration.sh
discovery-data/latest/src/postgresql-backup-restore-in-pod.sh
discovery-data/latest/src/reindex_archived_indices.sh
discovery-data/latest/src/tenant_index_template.json
discovery-data/latest/src/update-ingestion-conf.sh
discovery-data/latest/version.txt
discovery-data/latest/wddata-backup-restore.sh

This PR includes update for backup and restore scripts for Watson Discovery 4.7.0 on CP4D

Update script version for Watson Discovery 4.7.0 on CP4D

---

discovery-data/latest/src/minio-backup-restore-in-pod.sh

This PR includes following fix for backup and restore scripts of Watson Discovery on CP4D
- Fix MinIO error when scripts uses `--use-job` option.

Fix scripts for Watson Discovery 4.7.0 on CP4D

---

discovery-data/latest/all-backup-restore.sh
discovery-data/latest/mt-mt-migration.sh
discovery-data/latest/version.txt

This PR includes update for backup and restore scripts for Watson Discovery 4.7.1 on CP4D

Update script version for Watson Discovery 4.7.1 on CP4D

---

discovery-data/latest/lib/function.bash

This PR includes following fix for backup and restore scripts of Watson Discovery on CP4D.
- Modify label to get correct s3 configmap or secret

Fix scripts for Watson Discovery 4.7.x on CP4D

---

discovery-data/latest/reindex_es6_indices.sh

This PR includes a scripts to reindex old ElasticSearch index for Watson Discovery 4.8.0 on CP4D

Add scripts to reindex old ElasticSearch index for Watson Discovery 4.8.0 on CP4D

---

discovery-data/latest/elastic-backup-restore.sh
discovery-data/latest/lib/function.bash
discovery-data/latest/mt-mt-migration.sh
discovery-data/latest/version.txt

This PR includes update for backup and restore scripts for Watson Discovery 4.8.0 on CP4D

Update script for Watson Discovery 4.8.0 on CP4D

---

discovery-data/latest/all-backup-restore.sh
discovery-data/latest/lib/function.bash
discovery-data/latest/version.txt

This PR includes update for backup and restore scripts for Watson Discovery 4.8.2 on CP4D

Update script for Watson Discovery 4.8.2 on CP4D

---

discovery-data/latest/all-backup-restore.sh
discovery-data/latest/lib/function.bash
discovery-data/latest/version.txt

This PR includes update for backup and restore scripts for Watson Discovery 4.8.4 on CP4D

Update script for Watson Discovery 4.8.4 on CP4D

---

discovery-data/latest/all-backup-restore.sh
discovery-data/latest/elastic-backup-restore.sh
discovery-data/latest/lib/function.bash
discovery-data/latest/reindex_es6_indices.sh
discovery-data/latest/version.txt

This PR includes update for backup and restore scripts for Watson Discovery 5.0.0 on CP4D

Update script for Watson Discovery 5.0.0 on CP4D

---

discovery-data/latest/minio-backup-restore.sh
discovery-data/latest/version.txt

This PR includes update for backup and restore scripts for Watson Discovery 5.0.1 on CP4D.

Update script for Watson Discovery 5.0.1 on CP4D

---

discovery-data/latest/version.txt

Updating backup restore scripts for WD 5.0.3.

Updating backup restore scripts for WD 5.0.3

---

discovery-data/latest/lib/function.bash
discovery-data/latest/minio-backup-restore.sh
discovery-data/latest/src/minio-backup-restore-in-pod.sh
discovery-data/latest/version.txt

This PR includes update for backup and restore scripts for Watson Discovery 5.1.0.
- Updated the script version.
- Backup only discovery related buckets.
- Updated the postgres resource label selection.

feat: updating backup restore scripts for WD 5.1.0.

---

discovery-data/latest/lib/function.bash

This PR includes update for backup and restore scripts for Watson Discovery 4.8.8 on CP4D.

Updating watson discovery backup scripts for WD 4.8.8

---

discovery-data/latest/all-backup-restore.sh
discovery-data/latest/elastic-backup-restore.sh
discovery-data/latest/lib/function.bash
discovery-data/latest/lib/restore-updates.bash
discovery-data/latest/mt-mt-migration.sh
discovery-data/latest/src/elastic-backup-restore-in-pod.sh
discovery-data/latest/st-mt-migration.sh
discovery-data/latest/version.txt

Updated the backup restore script for WD 5.2.0. 
Change summary:
- Update version description
- Adapt to opensearch resources

feat: updating discovery backup restore script for 5.2.0.
